name: release

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - 'docker/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Iterate over charts
        run: |
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              CHART_NAME=$(basename "$chart")
              CHART_VERSION=$(grep 'version:' "$chart/Chart.yaml" | cut -f2 -d ':' | tr -d ' ')
              echo "Building and pushing Docker image for $CHART_NAME:$CHART_VERSION"

              # Set environment variables for each chart
              echo "CHART_NAME=$CHART_NAME" >> "$GITHUB_ENV"
              echo "CHART_VERSION=$CHART_VERSION" >> "$GITHUB_ENV"
            fi
          done

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ghcr.io/its-me-mayday/${{ env.CHART_NAME }}:stable
            ghcr.io/its-me-mayday/${{ env.CHART_NAME }}:latest
            ghcr.io/its-me-mayday/${{ env.CHART_NAME }}:${{ env.CHART_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"