name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
      - name: List all charts
        run: |
          echo "Listing all charts in the charts directory"
          ls -R ./charts
          
      - name: Package all charts
        run: |
          for chart in ./charts/*/Chart.yaml; do
            chart_dir=$(dirname "$chart")
            echo "Packaging chart in directory: $chart_dir"
            helm package "$chart_dir" --destination ./charts/packages
          done
          
      - name: Update index.yaml
        run: |
          echo "Updating index.yaml"
          helm repo index ./charts/packages --url https://its-me-mayday.github.io/AccioChart/
          
      - name: Commit and push updates
        run: |
          git add .
          git commit -m "Update Helm charts"
          git push origin main