name: release

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Iterate over charts and build images
        run: |
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              CHART_NAME=$(basename "$chart")
              CHART_VERSION=$(grep 'version:' "$chart/Chart.yaml" | cut -f2 -d ':' | tr -d ' ')
              echo "Building and pushing Docker image for $CHART_NAME:$CHART_VERSION"

              # Build and push the Docker image
              docker buildx build \
                --platform linux/amd64 \
                -t ghcr.io/its-me-mayday/$CHART_NAME:stable \
                -t ghcr.io/its-me-mayday/$CHART_NAME:latest \
                -t ghcr.io/its-me-mayday/$CHART_NAME:$CHART_VERSION \
                ./docker --file ./docker/Dockerfile --push
            fi
          done

  chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package charts and update index.yaml
        run: |
          # Package each chart
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "Packaging chart $chart"
              helm package "$chart"
            fi
          done

          # Update the index.yaml with the new charts
          helm repo index ./ --url https://its-me-mayday.github.io/AccioChart/

      - name: Commit and push changes
        run: |
          git add index.yaml
          git add *.tgz
          git commit -m "Update chart packages and index.yaml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}