name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**' 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          helm package charts/my-chart --destination ./packaged

      - name: Update Helm Repository Index
        run: |
          helm repo index ./packaged --url https://<username>.github.io/<repository>/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged